### ISSUE TITLE
GPDR Data Scrubbing for Actions

### ISSUE THREAD

**Issue by ryinthefields** [ryinthefields/hello-github-actions#3]
```
name: Netflix - GDPR Data Scrubbing Workflow

on:
  workflow_dispatch:  # Can be triggered manually or on a schedule (monthly scans)

jobs:
  scrub_sensitive_data:
   runs-on: ubuntu-latest (macos-latest or windows-latest)

   steps:
   
   # Step 1: Checkout the repository to get the latest code and commit history
   - name: Checkout repository
    uses: actions/checkout@v3

   # Step 2: Install git-filter-repo to enable commit history rewriting
   - name: Install git-filter-repo
    run: |
     sudo apt-get update
     sudo apt-get install -y git-filter-repo

   # Step 3: Define the sensitive data that needs to be scrubbed (email, names, etc.)
   - name: Define sensitive data to scrub
    run: |
     echo "EX_EMPLOYEE_EMAIL=employee@netflix.com" >> $GITHUB_ENV
     echo "EX_EMPLOYEE_NAME=Ryan Fields" >> $GITHUB_ENV
     # You can add more sensitive data types here (like phone numbers, usernames)

   # Step 4: Scrub the sensitive data from commit history
   - name: Scrub sensitive data from commit history
    run: |
     # Use git-filter-repo to scrub sensitive data (emails, usernames, etc.)
     git filter-repo --replace-text <(echo "employee@netflix.com==>redacted@netflix.com")
     git filter-repo --replace-text <(echo "Ryan Fields==>REDACTED_USER")
     # Add more replace-text commands for any other data

   # Step 5: Force push the cleaned commit history back to the repository
   - name: Push changes to the repository
    run: |
     git push --force  # Overwrite the commit history with scrubbed data

   # Step 6: Generate an audit log for compliance tracking
   - name: Generate audit log
    run: |
     echo "Scrubbed employee@netflix.com and Ryan Fields from commit history" >> audit_log.txt
     echo "Audit Log generated at $(date)" >> audit_log.txt
     echo "Detailed audit log: $(cat audit_log.txt)" > $GITHUB_ENV

   # Step 7: Upload the audit log as an artifact for Netflix to review
   - name: Upload audit log
    uses: actions/upload-artifact@v3
    with:
     name: scrubbed-audit-log
     path: audit_log.txt
```
